import "./globals.css";
import Footer from "./_ui/Footer";
import Header from "./_ui/Header";
import { CartProvider } from "./_context/CartContext";

export const metadata = {
  title: "Shopping Cart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className="">
        <CartProvider>
          <Header />
          <main>
            {children}
          </main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
